// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeLocation } from "./CodeLocation";

export type CreateReviewComment = {
  reviewId: string;
  body: string;
  replyTo: string | null;
  location: CodeLocation | null;
  embeds: { name: string; content: string }[];
};
