// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "./Author";
import type { Comment } from "./Comment";
import type { Never } from "./Never";

export type Issue = {
  id: string;
  author: Author;
  title: string;
  state: { status: "closed"; reason: "other" | "solved" } | { status: "open" };
  assignees: Array<Author>;
  discussion: Array<Comment<Never>>;
  labels: Array<string>;
  timestamp: number;
};
