// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IssueAction =
  | { type: "assign"; assignees: Array<string> }
  | { type: "edit"; title: string }
  | {
      type: "lifecycle";
      state:
        | { status: "closed"; reason: "other" | "solved" }
        | { status: "open" };
    }
  | { type: "label"; labels: Array<string> }
  | {
      type: "comment";
      /**
       * Comment body.
       */
      body: string;
      /**
       * Comment this is a reply to.
       * Should be [`None` | `null`] if it's the top-level comment.
       * Should be the root [`CommentId`] if it's a top-level comment.
       */
      replyTo: string | null;
      /**
       * Embeded content.
       */
      embeds: Array<string>;
    }
  | {
      type: "comment.edit";
      /**
       * Comment being edited.
       */
      id: string;
      /**
       * New value for the comment body.
       */
      body: string;
      /**
       * New value for the embeds list.
       */
      embeds: Array<string>;
    }
  | { type: "comment.redact"; id: string }
  | { type: "comment.react"; id: string; reaction: string; active: boolean };
