// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewIssue = {
  title: string;
  description: string;
  labels: Array<string>;
  assignees: Array<string>;
  embeds: { name: string; content: string }[];
};
