// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "./Author";
import type { CodeLocation } from "./CodeLocation";

export type Reaction = {
  emoji: string;
  authors: Array<Author>;
  location?: CodeLocation;
};
