// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "./Author";
import type { SupportedPayloads } from "./SupportedPayloads";

/**
 * Repos info.
 */
export type RepoInfo = {
  payloads: SupportedPayloads;
  delegates: Array<Author>;
  threshold: number;
  visibility: { type: "public" } | { type: "private"; allow?: string[] };
  rid: string;
  seeding: number;
};
