// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewEdit = {
  reviewId: string;
  verdict: string | null;
  summary: string | null;
  labels: Array<string>;
};
