// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "./Author";
import type { CodeLocation } from "./CodeLocation";
import type { Comment } from "./Comment";

export type Review = {
  id: string;
  author: Author;
  verdict?: "accept" | "reject";
  summary: string | null;
  comments: Array<Comment<CodeLocation>>;
  timestamp: bigint;
};
