// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RelayHealth } from "./RelayHealth";

/**
 * Flattened snapshot of the artifact node's status for the UI.
 *
 * The node's nested stat groups are flattened into one struct so the frontend
 * can render a flat list, except for the relays, which stay a list because
 * there is one entry per configured relay.
 */
export type ArtifactNodeStatus = {
  /**
   * Endpoint the node serves on, as a `radiroh://<base32>` URL.
   */
  endpointId: string;
  /**
   * Unix timestamp, in seconds, when the node bound its socket.
   */
  startedAtUnix: number;
  /**
   * Number of seeded `(rid, cid)` pairs.
   */
  seededCount: number;
  /**
   * Sum of logical artifact sizes across all seeded tags, in bytes.
   */
  seededBytesLogical: number;
  /**
   * Currently open connections.
   */
  connectionsActive: number;
  connectionsOpenedTotal: number;
  connectionsClosedTotal: number;
  connectionsDirectTotal: number;
  holepunchAttempts: number;
  pathsDirect: number;
  pathsRelayed: number;
  /**
   * Bytes sent across the wire, including discovery frames.
   */
  outBytes: number;
  /**
   * Bytes received across the wire, data only.
   */
  inBytes: number;
  /**
   * Per-home-relay status. Empty before a relay is selected, or when
   * relays are disabled.
   */
  relays: Array<RelayHealth>;
  /**
   * Relay the node would prefer, when a net report has landed.
   */
  preferredRelay?: string;
  /**
   * Whether a UDP round trip completed over IPv4, meaning direct UDP works.
   */
  udpV4: boolean;
  /**
   * Whether a UDP round trip completed over IPv6.
   */
  udpV6: boolean;
  /**
   * Set when no home relay is connected: peers that cannot holepunch may
   * be unable to reach this node.
   */
  relayUnreachable: boolean;
};
