// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the artifact binaries are installed.
 *
 * `rad-artifact node start` only starts the daemon; the daemon itself is the
 * separate `rad-artifact-node` binary, installed by its own crate. So the two
 * can be missing independently, and "install it" is different advice from
 * "start it".
 *
 * Uncached for the same reason as [`rad`]: the UI polls, so an install that
 * happens while the app runs takes effect without a restart.
 */
export type ArtifactBinaries = {
  /**
   * The `rad-artifact` CLI.
   */
  cli: boolean;
  /**
   * The `rad-artifact-node` seeding daemon.
   */
  node: boolean;
};
