// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One progress frame from an in-flight artifact download, flattened for the
 * UI and tagged with the content id so several downloads can share one event
 * channel.
 */
export type ArtifactProgress = {
  cid: string;
  /**
   * One of `connecting`, `tryingLocation`, `locationFailed`, `downloading`
   * or `exporting`.
   */
  phase: string;
  /**
   * Bytes moved so far, while downloading or exporting.
   */
  offset?: number;
  /**
   * Total bytes, when the node knows it.
   */
  total?: number;
};
