// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Flattened snapshot of the rad-artifact node's status for the UI. Mirrors
 * every field of the node's `Status` reply; the nested stat groups are
 * flattened so the frontend can render one flat list.
 */
export type ArtifactNodeStatus = {
  /**
   * Endpoint id the node serves on, as a `radiroh://<base32>` URL.
   */
  endpointId: string;
  /**
   * Unix timestamp (seconds) when the node bound its socket.
   */
  startedAtUnix: number;
  /**
   * Number of seeded `(rid, cid)` pairs.
   */
  seededCount: number;
  /**
   * Sum of logical artifact sizes across all seeded tags, in bytes.
   */
  seededBytesLogical: number;
  /**
   * Total bytes on disk under the node's store (includes db and scratch).
   */
  storeBytes: number;
  /**
   * Currently open connections.
   */
  connectionsActive: number;
  /**
   * Lifetime opened-handshaked connection count.
   */
  connectionsOpenedTotal: number;
  /**
   * Lifetime closed connection count.
   */
  connectionsClosedTotal: number;
  /**
   * Lifetime direct (non-relayed) connection count.
   */
  connectionsDirectTotal: number;
  /**
   * Lifetime holepunch attempts.
   */
  holepunchAttempts: number;
  /**
   * Path counter: direct.
   */
  pathsDirect: number;
  /**
   * Path counter: relayed.
   */
  pathsRelayed: number;
  /**
   * Bytes sent across the wire (includes disco frames).
   */
  outBytes: number;
  /**
   * Bytes received across the wire (data only).
   */
  inBytes: number;
};
