// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Connection status and measured latency of one home relay.
 */
export type RelayHealth = {
  url: string;
  connected: boolean;
  /**
   * Round-trip latency in milliseconds, when a probe has landed.
   */
  latencyMs?: number;
  /**
   * Most recent connection error while disconnected.
   */
  lastError?: string;
};
