// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../Author";
import type { Embed } from "../thread/Embed";

export type Edit = {
  author: Author;
  timestamp: number;
  body: string;
  embeds?: Array<Embed>;
};
