// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Patch state.
 */
export type State =
  | { status: "draft" }
  | {
      status: "open";
      /**
       * Revisions that were merged and are conflicting.
       */
      conflicts?: Array<[string, string]>;
    }
  | { status: "archived" }
  | {
      status: "merged";
      /**
       * The revision that was merged.
       */
      revision: string;
      /**
       * The commit in the target branch that contains the changes.
       */
      commit: string;
    };
