// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Auto-generated discriminant enum variants
 */
export type ErrorDiscriminants =
  | "EmbedsError"
  | "GitError"
  | "NodeError"
  | "IdentityError"
  | "RepoError"
  | "IssueError"
  | "PatchError"
  | "CryptoError"
  | "InboxError"
  | "ProfileError"
  | "ConfigError"
  | "CobStore"
  | "Io"
  | "Sqlite"
  | "Actions"
  | "CobStream"
  | "Database"
  | "Repository"
  | "Storage"
  | "SerdeJSON";
