// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Auto-generated discriminant enum variants
 */
export type NodeErrorDiscriminants =
  | "StartError"
  | "ConnectError"
  | "NotRunningError"
  | "RepoFetchError"
  | "ConfigError"
  | "PolicyStore"
  | "RuntimeError"
  | "Node";
