// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../Author";
import type { Location } from "./Location";
import type { Redaction } from "./Redaction";

/**
 * A single file published as part of a release, addressed by its content id.
 */
export type Artifact = {
  cid: string;
  name: string;
  author: Author;
  /**
   * Flattened across contributors: one entry per node/url pair.
   */
  locations: Array<Location>;
  attestations: Array<Author>;
  redactions: Array<Redaction>;
  metadata: Record<string, unknown>;
};
