// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A locally computed content id and size for a file or directory staged for
 * release, before it is registered on the COB.
 */
export type ArtifactDigest = { cid: string; sizeBytes: number };
