// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../Author";
import type { ArtifactKind } from "./ArtifactKind";
import type { Location } from "./Location";
import type { Redaction } from "./Redaction";

export type Artifact = {
  cid: string;
  name: string;
  kind: ArtifactKind;
  author: Author;
  locations: Array<Location>;
  attestations: Array<Author>;
  redactions: Array<Redaction>;
  /**
   * True when this device's iroh endpoint id appears as the host of
   * one of the location URLs we (the local DID) wrote — i.e. we are
   * actively advertising the artifact from the running process.
   */
  sharedFromHere: boolean;
  /**
   * True when our DID has at least one `iroh://` URL on the COB whose
   * host is *not* this device's iroh endpoint. Usually means we (or a
   * past install on a different machine, e.g. the CLI) advertised this
   * artifact from somewhere else. The bytes are not necessarily local.
   */
  sharedFromOther: boolean;
  /**
   * Free-form key/value annotations contributed by the artifact author
   * or repo delegates. Authorization is enforced upstream.
   */
  metadata?: Record<string, unknown>;
};
