// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../Author";

/**
 * A place an artifact can be fetched from, contributed by a single node.
 */
export type Location = { user: Author; url: string };
