// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../Author";

/**
 * A node flagging an artifact, with the reason it gave.
 */
export type Redaction = { user: Author; reason: string };
