// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Release counts bucketed by creator trust and artifact redaction. A redacted
 * release has every artifact redacted by a trusted party. A release with no
 * artifacts is not redacted.
 */
export type ReleaseCounts = {
  delegate: number;
  delegateRedacted: number;
  other: number;
  otherRedacted: number;
};
