// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The two disjoint author scopes of the release view. No local user is
 * trusted, so trusted means delegates.
 */
export type ReleaseScope = "trusted" | "untrusted";
