// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReleaseScope } from "./ReleaseScope";

/**
 * Which side of the release view the caller asks for.
 */
export type ReleaseFilter = {
  /**
   * Show releases and artifacts by delegates, or by everyone else.
   */
  scope: ReleaseScope;
  /**
   * Include artifacts redacted by their author or a delegate.
   */
  showRedacted: boolean;
};
