// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Release counts bucketed by creator trust and artifact redaction. A hidden
 * release has no artifact left once those redacted by a trusted party are
 * removed.
 */
export type ReleaseCounts = {
  delegate: number;
  delegateHidden: number;
  other: number;
  otherHidden: number;
};
