// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../Author";
import type { Artifact } from "./Artifact";

/**
 * A release, keyed by a commit and optionally an annotated tag. The COB has
 * no title of its own: `title` and `tagName` are resolved from the tag or
 * commit message, and are absent when they cannot be read.
 */
export type Release = {
  id: string;
  oid: string;
  tag?: string;
  tagName?: string;
  title?: string;
  createdAt: number;
  creator: Author;
  artifacts: Array<Artifact>;
};
