// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../Author";
import type { Artifact } from "./Artifact";

export type Release = {
  id: string;
  oid: string;
  /**
   * OID of the annotated tag that was recorded alongside the commit,
   * if any. `None` means the release was created from a bare commit.
   */
  tag?: string;
  /**
   * Refname of the tag pointed at by `tag`, resolved on the server so
   * the UI doesn't need to fan out a separate `list_tags` lookup per
   * release. Omitted when the tag has been deleted locally.
   */
  tagName?: string;
  /**
   * DID of the user who authored this release COB.
   */
  creator: Author;
  /**
   * Subject line of the released commit, resolved on the server so the
   * list view can render it without an extra round-trip per row.
   */
  commitSummary?: string;
  timestamp: number;
  artifacts: Array<Artifact>;
};
