// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far the caller widened the default, delegate-scoped release view.
 */
export type ReleaseFilter = {
  /**
   * Include releases and artifacts authored by non-delegates.
   */
  allAuthors: boolean;
  /**
   * Include artifacts redacted by their author or a delegate.
   */
  showRedacted: boolean;
};
