// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeRange } from "./CodeRange";

export type CodeLocation = {
  commit: string;
  path: string;
  old: CodeRange | null;
  new: CodeRange | null;
};
