// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeLocation } from "./CodeLocation";
import type { Embed } from "./Embed";

export type NewPatchComment = {
  id: string;
  revision: string;
  body: string;
  replyTo?: string;
  location?: CodeLocation;
  embeds?: Array<Embed>;
};
