// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Service configuration.
 */
export type Config = {
  /**
   * Node Public Key in NID format.
   */
  publicKey: string;
  /**
   * Node alias.
   */
  alias: string;
  /**
   * Default seeding policy.
   */
  seedingPolicy: { default: "allow"; scope: "followed" | "all" } | {
    default: "block";
  };
  /**
   * Public explorer URL template, e.g. `https://radicle.network/nodes/$host/$rid$path`.
   */
  publicExplorer: string;
  /**
   * Preferred seed addresses, in priority order. Used to pick a host for
   * explorer links.
   */
  preferredSeeds: Array<string>;
};
