// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The git binary the app resolved, for display in the settings.
 */
export type GitInfo = {
  /**
   * Absolute path of the binary. Unset when none was found.
   */
  path?: string;
  /**
   * What it answers `--version` with. Unset when none was found.
   */
  version?: string;
};
