// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The resolved git binary, for display in the settings. Both fields are unset
 * when no git was found.
 */
export type GitInfo = { path?: string; version?: string };
