// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A node offered as a mention, with the trust signals needed to tell apart
 * several nodes claiming the same alias.
 *
 * Aliases are self-declared and unverified, so any number of nodes can call
 * themselves the same thing. Whether the local node follows a candidate, and
 * whether it is the local node itself, is the only information available here
 * to rank and label them; repo delegates are marked by the frontend, which
 * already holds the identity document.
 */
export type AliasSuggestion = {
  did: string;
  alias?: string;
  /**
   * The local node follows this node, so the alias is one the user chose to
   * record rather than one picked up from gossip.
   */
  followed: boolean;
  /**
   * This is the local node.
   */
  isSelf: boolean;
};
