// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CacheEvent = { "event": "started"; "data": { rid: string } } | {
  "event": "progress";
  "data": { rid: string; oid: string; current: number; total: number };
} | { "event": "finished"; "data": { rid: string } };
