// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiffOptions = {
  base: string;
  head: string;
  unified: number | null;
  highlight: boolean | null;
};
