// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "./Author";

/**
 * Everything that can be done in the system is represented by an `Op`.
 * Operations are applied to an accumulator to yield a final state.
 */
export type Operation<A> = {
  id: string;
  actions: Array<A>;
  author: Author;
  timestamp: number;
};
