// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An issue or patch whose title or ID matched a search, across every
 * repository in the COB cache.
 */
export type SearchResult = {
  rid: string;
  id: string;
  title: string;
  status: string;
};
