// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Stats = {
  files_changed: number;
  insertions: number;
  deletions: number;
};
