// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The SSH representations of a user's public key.
 */
export type Ssh = {
  /**
   * The SSH long key, as printed by `ssh-add -L`.
   */
  full: string;
  /**
   * The SSH key fingerprint, as printed by `ssh-add -l`.
   */
  hash: string;
};
