// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ssh } from "./Ssh";

/**
 * A user of the Radicle network, as known to the local node.
 */
export type User = {
  did: string;
  publicKey: string;
  alias?: string;
  ssh: Ssh;
  /**
   * Whether the local node follows this user.
   */
  following: boolean;
  /**
   * Whether this is the local node's own identity.
   */
  isLocal: boolean;
};
