// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Commit } from "../repo/Commit";

export type Blob = {
  id: string;
  binary: boolean;
  commit: Commit;
  mimeType: string;
  content: string;
};
