// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EntryKind = { "tree": string } | { "blob": string } | {
  "submodule": { id: string; url: string | null };
};
