// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a member's own actor repository asserts the membership back.
 */
export type Attestation =
  | "attested"
  | "unconfirmed"
  | "unknown"
  | "notApplicable";
