// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../cob/Author";
import type { SignatureStatus } from "./SignatureStatus";

export type CommitSignature = {
  status: SignatureStatus;
  /**
   * The signing key, as a Radicle identity. Git signs with whatever
   * `user.signingKey` points at; when an author points that at their Radicle
   * key, the Ed25519 key carried in the signature is also their node ID and
   * so resolves to a DID. Absent when the key is not Ed25519.
   */
  signer?: Author;
  /**
   * Whether the signer is a delegate of this repository.
   */
  delegate: boolean;
  /**
   * Whether the signer was a delegate under some earlier identity revision,
   * but is not one now.
   *
   * This is deliberately an existence claim over the identity history rather
   * than a claim about the moment this commit was signed. Nothing in a commit
   * object points at an identity revision, so the only way to date a commit
   * against the delegate set is its committer timestamp — which the signer
   * chooses freely, and can therefore backdate into a delegacy window they no
   * longer hold.
   */
  formerDelegate: boolean;
  /**
   * Whether the signer has a remote in this repository.
   */
  remote: boolean;
  /**
   * Whether the signing key corresponds to a node we have any evidence for:
   * it is a delegate, was one, has a remote here, or is a node the local
   * node knows by alias.
   *
   * Signing a git commit with a Radicle key is a convention an author opts
   * into, not something the protocol does, so any Ed25519 key encodes to a
   * syntactically valid DID whether or not a node behind it exists. Without
   * one of the above, that DID is not evidence of a Radicle identity and
   * must not be presented as one.
   */
  known: boolean;
  /**
   * OpenSSH fingerprint of the signing key, in the form
   * `git show --show-signature` prints. Present whenever the key is Ed25519.
   */
  fingerprint?: string;
};
