// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an org member is named in `.radicle/org.json`.
 */
export type MemberKind = "actor" | "key";
