// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectPayloadMeta = {
  head: string;
  issues: { open: number; closed: number };
  patches: { open: number; draft: number; archived: number; merged: number };
  lastCommitTimestamp: number;
};
