// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tag } from "./Tag";

export type Remote = {
  id: string;
  alias?: string;
  delegate: boolean;
  branches: { [key in string]: string };
  tags: { [key in string]: Tag };
};
