// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A team named by a repository's `dev.radicle.teams.v1` identity-document
 * payload, together with whether that team lists the repository back in its
 * own `.radicle/team.json`.
 */
export type RepoTeam = { rid: string; name: string | null; mutual: boolean };
