// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../cob/Author";
import type { SupportedPayloads } from "./SupportedPayloads";
import type { Visibility } from "./Visibility";

export type RepoInfo = {
  payloads: SupportedPayloads;
  delegates: Array<Author>;
  threshold: number;
  visibility: Visibility;
  rid: string;
  /**
   * How many nodes on the network are known to seed this repository.
   */
  seeding: number;
  /**
   * Whether the local node seeds this repository. When false the repository
   * is only in local storage, which `rad ls --all` shows as "local".
   */
  seeded: boolean;
  lastCommitTimestamp: number;
};
