// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../cob/Author";
import type { SupportedPayloads } from "./SupportedPayloads";
import type { Visibility } from "./Visibility";

export type RepoInfo = {
  payloads: SupportedPayloads;
  delegates: Array<Author>;
  threshold: number;
  visibility: Visibility;
  rid: string;
  seeding: number;
  lastCommitTimestamp: number;
};
