// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Canonical } from "./Canonical";
import type { Remote } from "./Remote";

export type RepoRefs = { canonical: Canonical; remotes: Array<Remote> };
