// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An org named by a repository's `xyz.radicle.orgs` identity-document
 * payload, together with whether that org lists the repository back in its
 * own `.radicle/org.json`.
 */
export type RepoOrg = { rid: string; name: string | null; mutual: boolean };
