// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RepoSummary = {
  rid: string;
  name: string;
  private: boolean;
  /**
   * False for a repository that is in storage but not seeded, which
   * `rad ls --all` shows as "local".
   */
  seeding: boolean;
};
