// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeedingPolicy } from "./SeedingPolicy";

export type RepoSummary = {
  rid: string;
  name: string;
  seedingPolicy: SeedingPolicy;
};
