// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../cob/Author";
import type { Status } from "./Status";

export type Run = { runId: string; node: Author; status: Status; log: string };
