// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which remotes of a seeded repository the node replicates.
 */
export type SeedingScope = "followed" | "all";
