// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeedingScope } from "./SeedingScope";

/**
 * What the local node does with a repository. Mirrors the policy and scope
 * columns `rad seed` prints.
 */
export type SeedingPolicy = { "type": "allow"; scope: SeedingScope } | {
  "type": "block";
};
