// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of checking a commit's `gpgsig` header.
 *
 * Absence of the header is not represented here: an unsigned commit carries no
 * [`CommitSignature`] at all.
 */
export type SignatureStatus = "verified" | "invalid" | "unsupported";
