// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncedAt } from "./SyncedAt";

export type SyncStatus = {
  "status": "synced";
  /**
   * At what ref was the remote synced at.
   */
  at: SyncedAt;
} | {
  "status": "outOfSync";
  /**
   * Local head of our `rad/sigrefs`.
   */
  local: SyncedAt;
  /**
   * Remote head of our `rad/sigrefs`.
   */
  remote: SyncedAt;
};
