// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Tag = {
  oid: string;
  /**
   * Tagger time for annotated tags, otherwise the commit time of the
   * tagged commit. Seconds since epoch.
   */
  timestamp: number;
};
