// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Tagger = {
  name: string;
  email: string;
  /**
   * Tagger time. Seconds since epoch.
   */
  timestamp: number;
};
