// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TagRef = {
  /**
   * Short tag refname, e.g. `v1.0.0`.
   */
  name: string;
  /**
   * Tag OID for annotated tags, commit OID for lightweight tags.
   * This is the OID stored on the artifact COB's `tag` field for
   * annotated tags.
   */
  oid: string;
  /**
   * The commit this tag points at. For lightweight tags this equals
   * `oid`; for annotated tags it's the commit reachable via the tag
   * object's target.
   */
  commit: string;
  annotated: boolean;
  message?: string;
};
