// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attestation } from "./Attestation";
import type { MemberKind } from "./MemberKind";

/**
 * One entry of a team's member roster, with the member's half of the
 * attestation resolved where it can be read.
 */
export type TeamMember = {
  /**
   * The entry exactly as written: a `rad:` RID or a `did:key:` DID.
   */
  id: string;
  kind: MemberKind;
  attestation: Attestation;
  /**
   * The `name` from the member's profile, when readable.
   */
  name: string | null;
};
