// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A revision and a path within it, as split out of an explorer tree URL.
 */
export type TreePath = { revision: string; path: string };
