// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../cob/Author";

export type Visibility = { "type": "public" } | {
  "type": "private";
  allow?: Array<Author>;
};
