// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeLocation } from "../thread/CodeLocation";
import type { Verdict } from "./Verdict";

export type CreateReviewArgs = {
  rid: string;
  revision: string;
  verdict: Verdict | null;
  summary: string | null;
  labels: Array<string>;
  comments: Array<{ body: string; location: CodeLocation | null }>;
};
