// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../Author";
import type { Reviewer } from "./Reviewer";
import type { State } from "./State";

export type Patch = {
  id: string;
  author: Author;
  title: string;
  base: string;
  head: string;
  state: State;
  targetBranch?: string;
  assignees: Array<Author>;
  labels: Array<string>;
  timestamp: number;
  revisionIds: Array<string>;
  commentCount: number;
  reviewers: Array<Reviewer>;
};
