// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../Author";
import type { Verdict } from "./Verdict";

/**
 * One published review, flattened so the patch list can summarise a patch
 * without loading its revisions.
 *
 * There is an entry per review, not per reviewer: the protocol allows one
 * review per author per revision, so the same person appears once for each
 * revision they reviewed. `revision_number` is the reviewed revision's 1-based
 * position in the patch timeline, which together with `revision_ids.len()`
 * tells the UI whether a review still covers the current head.
 */
export type Reviewer = {
  author: Author;
  verdict?: Verdict;
  revisionNumber: number;
  /**
   * Whether the reviewer is a delegate, so their verdict can be told apart
   * from a non-delegate's at a glance.
   */
  delegate: boolean;
};
