// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../Author";
import type { Verdict } from "./Verdict";

export type Reviewer = { author: Author; verdict?: Verdict };
