// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../Author";
import type { CodeLocation } from "../thread/CodeLocation";
import type { Comment } from "../thread/Comment";

export type Review = {
  id: string;
  author: Author;
  verdict?: "accept" | "reject";
  summary?: string;
  comments?: Array<Comment<CodeLocation>>;
  timestamp: number;
};
