// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Verdict } from "./Verdict";

export type ReviewInit = {
  "type": "ReviewInit";
  revision: string;
  summary?: string;
  verdict?: Verdict;
  labels?: Array<string>;
};
