// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type State =
  | { status: "draft" }
  | { status: "open"; conflicts?: Array<[string, string]> }
  | { status: "archived" }
  | { status: "merged"; revision: string; commit: string };
