// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EofNewLine } from "./EofNewLine";
import type { FileStats } from "./FileStats";
import type { Hunks } from "./Hunks";

export type DiffContent = { "type": "binary" } | {
  "type": "plain";
  hunks: Hunks;
  stats: FileStats;
  eof: EofNewLine;
} | { "type": "empty" };
