// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileDiff } from "./FileDiff";
import type { Stats } from "./Stats";

export type Diff = { files: Array<FileDiff>; stats: Stats };
