// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileMode } from "./FileMode";

export type DiffFile = { oid: string; mode: FileMode };
