// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileStats } from "./FileStats";

/**
 * What kind of change a file carries. `Plain` keeps its stats; the other two
 * exist so the app can label a file it cannot render lines for.
 */
export type DiffContent = { "type": "binary" } | {
  "type": "plain";
  stats: FileStats;
} | { "type": "empty" };
