// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Added } from "./Added";
import type { Copied } from "./Copied";
import type { Deleted } from "./Deleted";
import type { Modified } from "./Modified";
import type { Moved } from "./Moved";

export type FileDiff =
  | { "status": "added" } & Added
  | { "status": "deleted" } & Deleted
  | { "status": "modified" } & Modified
  | { "status": "moved" } & Moved
  | { "status": "copied" } & Copied;
