// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Modification } from "./Modification";

export type Hunk = {
  header: string;
  lines: Array<Modification>;
  old: { start: number; end: number };
  new: { start: number; end: number };
};
