// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloseReason } from "./CloseReason";

export type State = { "status": "closed"; reason: CloseReason } | {
  "status": "open";
};
