// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../cob/Author";

/**
 * Whose refs count towards a canonical ref.
 */
export type Allowed = { "type": "delegates" } | {
  "type": "set";
  dids: Array<Author>;
};
