// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Allowed } from "./Allowed";

/**
 * One `refs/...` pattern and the rule that decides its canonical value.
 */
export type CanonicalRefRule = {
  pattern: string;
  allow: Allowed;
  /**
   * DIDs from `allow` that must agree on a commit or tag, in their own
   * namespace, for it to become canonical.
   */
  threshold: number;
};
