// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../cob/Author";

/**
 * One `refs/...` pattern and the rule that decides its canonical value.
 */
export type CanonicalRefRule = {
  /**
   * The ref pattern the rule applies to, e.g. `refs/tags/releases/*`.
   */
  pattern: string;
  /**
   * Who may sign off on this ref. Empty means the rule delegates to the
   * document's delegate set rather than naming keys.
   */
  allow: Array<Author>;
  /**
   * True when the rule defers to the document's delegates.
   */
  delegates: boolean;
  threshold: number | null;
};
