// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../cob/Author";
import type { Visibility } from "../repo/Visibility";
import type { PayloadOperation } from "./PayloadOperation";

/**
 * A single field-level difference between a revision and its parent.
 */
export type Change =
  | { "type": "delegateAdded"; delegate: Author }
  | { "type": "delegateRemoved"; delegate: Author }
  | { "type": "thresholdChanged"; from: number; to: number }
  | { "type": "visibilityChanged"; from: Visibility; to: Visibility }
  | { "type": "nameChanged"; from: string; to: string }
  | { "type": "descriptionChanged"; from: string; to: string }
  | { "type": "defaultBranchChanged"; from: string; to: string }
  | { "type": "payloadChanged"; payload: string; operation: PayloadOperation };
