// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../cob/Author";
import type { Visibility } from "../repo/Visibility";
import type { CanonicalRefRule } from "./CanonicalRefRule";
import type { Project } from "./Project";

export type Doc = {
  version: number;
  delegates: Array<Author>;
  /**
   * Delegates that must agree on a commit, by having it on their own copy
   * of the default branch, for it to become canonical. This is *not* what
   * governs changes to this document — see `majority`.
   */
  threshold: number;
  /**
   * Delegate signatures needed to adopt a new revision of this document:
   * a simple majority of the delegate set.
   */
  majority: number;
  visibility: Visibility;
  project: Project | null;
  /**
   * The canonical-refs rules heartwood applies: those of the
   * `xyz.radicle.crefs` payload plus the default-branch rule it synthesizes
   * from the project payload when there is none.
   */
  canonicalRefs: Array<CanonicalRefRule>;
  /**
   * Why heartwood rejects the document's canonical-refs rules, if it does.
   * `canonical_refs` then holds the payload's rules as written.
   */
  canonicalRefsError?: string;
  /**
   * All payload ids, including ones the UI doesn't render.
   */
  payloadIds: Array<string>;
  /**
   * The document pretty-printed as `rad inspect --identity` prints it.
   */
  raw: string;
};
