// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../cob/Author";
import type { Visibility } from "../repo/Visibility";
import type { CanonicalRefRule } from "./CanonicalRefRule";
import type { Project } from "./Project";

/**
 * A snapshot of an identity document.
 */
export type Doc = {
  version: number;
  delegates: Array<Author>;
  /**
   * Delegate signatures needed to make a ref canonical. This is *not* what
   * governs changes to this document — see `majority`.
   */
  threshold: number;
  /**
   * Delegate signatures needed to adopt a new revision of this document:
   * a simple majority of the delegate set.
   */
  majority: number;
  visibility: Visibility;
  project: Project | null;
  /**
   * Canonical-refs rules from the `xyz.radicle.crefs` payload, if any.
   */
  canonicalRefs: Array<CanonicalRefRule>;
  /**
   * Payload ids present on the document, including ones this app has no
   * dedicated rendering for.
   */
  payloadIds: Array<string>;
  /**
   * The document as stored, pretty-printed. Nothing above is hidden from
   * this: it is the escape hatch for fields the UI does not model.
   */
  raw: string;
};
