// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Doc } from "./Doc";
import type { Revision } from "./Revision";

/**
 * The identity of a repository: the document as it stands now, plus every
 * revision that was ever proposed to it.
 */
export type Identity = {
  rid: string;
  /**
   * The revision whose commit `refs/rad/id` points at. Unset if the
   * identity COB has no accepted revision for that commit.
   */
  current?: string;
  /**
   * The current document, read from `refs/rad/id`.
   */
  doc: Doc;
  /**
   * Every revision, newest first.
   */
  revisions: Array<Revision>;
};
