// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Doc } from "./Doc";
import type { Revision } from "./Revision";

/**
 * The identity of a repository: the document as it stands now, plus every
 * revision that was ever proposed to it.
 */
export type Identity = {
  rid: string;
  /**
   * Revision id of the document currently in force.
   */
  current: string;
  /**
   * The document currently in force.
   */
  doc: Doc;
  /**
   * Every revision, newest first.
   */
  revisions: Array<Revision>;
};
