// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../cob/Author";
import type { Change } from "./Change";
import type { State } from "./State";

/**
 * A proposed change to the identity document.
 */
export type Revision = {
  id: string;
  blob: string;
  title: string;
  description: string;
  state: State;
  author: Author;
  timestamp: number;
  parent?: string;
  accepted: Array<Author>;
  rejected: Array<Author>;
  /**
   * Delegates that have not given a verdict. Together with `accepted` and
   * `rejected` these are the delegates of the parent document, the only
   * ones whose verdicts count. Empty for the root revision.
   */
  pending: Array<Author>;
  /**
   * Signatures needed to adopt the revision: a majority of the parent
   * document's delegates. Unset for the root revision, which is accepted
   * on creation.
   */
  majority?: number;
  /**
   * The document as it would stand if this revision were adopted,
   * pretty-printed like `Doc::raw`.
   */
  raw: string;
  /**
   * What this revision changes relative to its parent, in domain terms
   * rather than as a text diff.
   */
  changes: Array<Change>;
  /**
   * The same change as a unified diff of the pretty-printed documents.
   */
  diff: string;
};
