// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../cob/Author";
import type { Change } from "./Change";
import type { Doc } from "./Doc";
import type { State } from "./State";

/**
 * A proposed change to the identity document.
 */
export type Revision = {
  id: string;
  /**
   * The document blob this revision points at.
   */
  blob: string;
  title: string;
  description: string;
  state: State;
  author: Author;
  timestamp: number;
  parent?: string;
  /**
   * Delegates that signed the revision.
   */
  accepted: Array<Author>;
  /**
   * Delegates that voted against it.
   */
  rejected: Array<Author>;
  /**
   * Whether the accepting signatures met the threshold in force.
   */
  quorum: boolean;
  /**
   * The document as it would stand if this revision were adopted.
   */
  doc: Doc;
  /**
   * What this revision changes relative to its parent, in domain terms
   * rather than as a text diff.
   */
  changes: Array<Change>;
};
