// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RedactedReason } from "./RedactedReason";
import type { RejectedReason } from "./RejectedReason";

export type State = { "status": "active" } | { "status": "accepted" } | {
  "status": "rejected";
  reason: RejectedReason;
} | { "status": "redacted"; reason: RedactedReason };
