// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { Author } from "../Author";

export type IssueOps = {
  id: string;
  action: Action;
  timestamp: number;
  author: Author;
};
