// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectPayloadData } from "./ProjectPayloadData";
import type { ProjectPayloadMeta } from "./ProjectPayloadMeta";

export type ProjectPayload = {
  data: ProjectPayloadData;
  meta: ProjectPayloadMeta;
};
