// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectPayload } from "./ProjectPayload";

export type SupportedPayloads = { "xyz.radicle.project"?: ProjectPayload };
