// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Repository visibility.
 */
export type Visibility =
  | { type: "public" }
  | { type: "private"; allow?: Array<string> };
