// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublishChange } from "./PublishChange";
import type { PublishKind } from "./PublishKind";

/**
 * The repository we most recently published to, and whether that publication
 * has been seen elsewhere.
 */
export type LatestPublish = {
  rid: string;
  /**
   * Project name, when the repository has a project payload.
   */
  name?: string;
  /**
   * Commit time of our `rad/sigrefs` there, in milliseconds: when we last
   * published to it.
   */
  publishedAt: number;
  /**
   * When another node was last recorded holding that exact head, in
   * milliseconds. Absent while it has reached no one.
   */
  confirmedAt?: number;
  /**
   * How many other nodes were recorded holding that exact head. Zero while
   * it has reached no one.
   */
  confirmedBy: number;
  /**
   * What kind of thing that publication touched.
   */
  kind: PublishKind;
  /**
   * Whether it was created, revised, or otherwise changed.
   */
  change: PublishChange;
  /**
   * The last collaborative-object action in that publication, by its serde
   * tag, e.g. `comment` or `review`. Only resolved when the publication
   * moved just an object, which is the case a ref diff alone cannot
   * describe.
   */
  action?: string;
  /**
   * Title of the object that action was on.
   */
  title?: string;
};
