// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncSummary } from "./SyncSummary";

/**
 * Status of the local node, independent of any repository.
 */
export type NodeStatus = {
  /**
   * Whether the node daemon is running.
   */
  running: boolean;
  /**
   * Our own Node ID.
   */
  nid: string;
  /**
   * Our own alias.
   */
  alias: string;
  /**
   * Addresses the node listens on for inbound connections. Empty when the
   * node is not configured to accept them.
   */
  listenAddrs: Array<string>;
  /**
   * Number of peers we currently hold a connection to. Deliberately not
   * paired with a total: the node's session table also holds disconnected
   * entries awaiting retry, so any total reads as a cap that does not exist.
   */
  connectedPeers: number;
  /**
   * Number of repositories we have an "allow" seeding policy for.
   */
  seeding: number;
  /**
   * How far our own work has propagated to other nodes.
   */
  sync: SyncSummary;
};
