// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a publication changed the thing it touched.
 *
 * A patch's branch and its collaborative object move together for a revision,
 * but a comment, an edit or a state change moves only the object, so the two
 * are distinguishable.
 */
export type PublishChange = "created" | "revised" | "updated";
