// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a publication changed, derived from which refs moved between our
 * current `rad/sigrefs` and the one before it.
 *
 * Paired with [`LatestPublish::created`] to tell a new object apart from a
 * change to an existing one.
 */
export type PublishKind = "patch" | "issue" | "branch" | "mixed";
