// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeedStatus } from "./SeedStatus";

/**
 * Sync status of a single repository across the seeds that hold it.
 */
export type RepoSyncStatus = {
  /**
   * Seeds known to hold this repository, most recently synced first.
   */
  seeds: Array<SeedStatus>;
  /**
   * Number of seeds that hold our refs at our local head.
   */
  synced: number;
  /**
   * Number of seeds that report a sync status for our refs.
   */
  tracked: number;
  /**
   * How many seeds the protocol aims to replicate to. Gives `synced` a
   * denominator that means something: `tracked` counts every node that ever
   * announced this repo, so a ratio against it reads as near-empty even when
   * replication is healthy.
   */
  target: number;
  /**
   * Whether the node answered. When false the seed list is empty because the
   * node could not be queried, not because no seeds hold the repository, and
   * callers should say so rather than reporting zero seeds.
   */
  available: boolean;
};
