// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncStatus } from "../repo/SyncStatus";

/**
 * One seed's view of a repository.
 */
export type SeedStatus = {
  nid: string;
  alias?: string;
  /**
   * Whether we currently hold a connection to this seed.
   */
  connected: boolean;
  /**
   * How far this seed has replicated our refs. Absent when the seed reports
   * no sync status for our namespace, which is the case for repositories we
   * have never contributed to.
   */
  sync?: SyncStatus;
};
