// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LatestPublish } from "./LatestPublish";

/**
 * How far the local node's own work has reached other nodes.
 *
 * Derived from the node's `repo-sync-status` table, which records the head of
 * *our* `rad/sigrefs` that each other node was last seen holding. Comparing
 * that against our current head is the only thing we can honestly claim: it
 * says some node has our latest signed refs, not that the network as a whole
 * is in sync, which is unknowable in a peer-to-peer system.
 */
export type SyncSummary = {
  /**
   * Repositories we seed and have signed refs in, i.e. the ones we have
   * something of our own to propagate.
   */
  repos: number;
  /**
   * Of those, how many have at least one other node holding our current
   * `rad/sigrefs` head.
   */
  confirmed: number;
  /**
   * The most recently published of those repositories. Absent when we have
   * published nothing anywhere.
   */
  latest?: LatestPublish;
};
