// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Service configuration.
 */
export type Config = {
  /**
   * Node alias.
   */
  publicKey: string;
  /**
   * Node alias.
   */
  alias: string;
  /**
   * Default seeding policy.
   */
  seedingPolicy:
    | { default: "allow"; scope: "followed" | "all" }
    | { default: "block" };
};
