// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "./Author";

export type Edit = {
  author: Author;
  timestamp: bigint;
  body: string;
  embeds: { name: string; content: string };
};
