// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `Infallible` type does not have a `Serialize`/`Deserialize`
 * implementation. The `Never` type imitates `Infallible` and
 * provides the derived implementations.
 */
export type Never = never;
