// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "./Author";

export type Patch = {
  id: string;
  author: Author;
  title: string;
  state:
    | {
        status: "draft";
      }
    | {
        status: "open";
        conflicts: [string, string][];
      }
    | {
        status: "archived";
      }
    | {
        status: "merged";
        revision: string;
        commit: string;
      };
  assignees: Array<Author>;
  labels: Array<string>;
  timestamp: number;
  revisionCount: number;
};
