[package]
name = "radicle-board"
description = "Radicle board collaborative object"
version = "0.1.0"
edition.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
log = { version = "0.4" }
radicle = { version = "0.25" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
thiserror = { version = "2.0.12" }

[dev-dependencies]
radicle = { version = "0.25", features = ["test"] }
