// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityKind } from "./ActivityKind";

/**
 * Something this person contributed, for the cross-repo activity feed.
 */
export type ActivityItem = {
  rid: string;
  kind: ActivityKind;
  /**
   * The COB to open: the patch or issue id. A revision item carries the id
   * of the patch it belongs to, since revisions are not addressable on
   * their own.
   */
  id: string;
  /**
   * Set only on revision items, and only to keep them distinct from each
   * other and from their patch.
   */
  revisionId?: string;
  /**
   * 1-based position of this revision among its patch's revisions, and how
   * many there are. Filled in from the patch's delivered revision order,
   * not from the cache — see `Patches::annotate_revision_positions`.
   */
  revisionPosition?: number | undefined;
  revisionTotal?: number | undefined;
  title: string;
  status: string;
  timestamp: number;
};
