// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of thing an activity item records. `Revision` is a follow-up
 * revision pushed to someone else's or one's own existing patch, which is
 * distinct from opening the patch in the first place.
 */
export type ActivityKind = "patch" | "revision" | "issue";
