// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One day's contribution count, for the calendar heatmap. Days with no
 * contributions are omitted; the caller fills the grid.
 */
export type ContributionDay = {
  /**
   * `YYYY-MM-DD`, bucketed in UTC.
   */
  date: string;
  count: number;
};
