// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one person authored in one repo, counted from the COB cache.
 */
export type RepoContribution = {
  rid: string;
  patchesAuthored: number;
  issuesAuthored: number;
  /**
   * When this person last contributed here, in epoch milliseconds. Counts
   * follow-up revisions as well as opened patches and issues, so it is the
   * last time they touched the repo at all.
   */
  lastContribution?: number | undefined;
};
