// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "../issue/Action";
import type { ActionWithAuthor } from "./ActionWithAuthor";
import type { RefUpdate } from "./RefUpdate";
import type { State } from "../issue/State";

export type Issue = {
  rowId: string;
  id: string;
  update: RefUpdate;
  title: string;
  timestamp: number;
  status: State;
  actions: Array<ActionWithAuthor<Action>>;
};
