// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationItem } from "./NotificationItem";

export type NotificationsByRepo = {
  rid: string;
  name: string;
  notifications: Array<Array<NotificationItem>>;
  count: number;
};
