// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Issue } from "./Issue";
import type { Patch } from "./Patch";

export type NotificationItem =
  | { "type": "issue" } & Issue
  | { "type": "patch" } & Patch;
