// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the local node relates to a notified issue or patch. Derived from the
 * object itself rather than from the unread activity, so it holds regardless
 * of what the unread range happens to contain.
 */
export type Relevance = {
  /**
   * The local node opened it.
   */
  authored: boolean;
  /**
   * The local node is assigned to it.
   */
  assigned: boolean;
  /**
   * The local node has commented on it or reviewed it.
   */
  participating: boolean;
};
