// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Column } from "./Column";
import type { Placement } from "./Placement";

export type Board = {
  id: string;
  name: string;
  createdAt: number;
  columns: Array<Column>;
  cards: Array<Placement>;
};
