// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The issues a patch mentions by id in its title or description.
 */
export type PatchLink = { patch: string; issues: Array<string> };
