// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../Author";
import type { Card } from "./Card";

export type Placement = {
  card: Card;
  column: string;
  position: string;
  movedBy: Author;
  movedAt: number;
};
