#!/bin/sh
set -e

cargo check --manifest-path ./crates/radicle-tauri/Cargo.toml
cargo clippy --manifest-path ./crates/radicle-tauri/Cargo.toml -- -Dwarnings
cargo fmt --manifest-path ./crates/radicle-tauri/Cargo.toml --check
