// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Paint } from "./Paint";

/**
 * A styled string that does not contain any `'\n'`.
 */
export type Label = Paint;
