// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Label } from "./Label";

/**
 * A line of text that has styling and can be displayed.
 */
export type Line = { items: Array<Label> };
