// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A structure encapsulating an item and styling.
 */
export type Paint = { item: string; style: string | null };
