when:
  - event: pull_request
  - event: push
    branch: main
  - event: manual

variables:
  - &plugin-sccache-read-only
    s3-bucket: "build-caches"
    s3-endpoint: "https://minio-api.radworks.garden"
    s3-key-prefix: "radicle-desktop"
    save-if: "false"
    s3-access-key:
      from_secret: minio_access_key
    s3-secret-access-key:
      from_secret: minio_secret_key

steps:
  read_cache:
    image: quay.io/radicle_garden/plugin-sccache:latest
    volumes:
      - sccache:/sccache_data
    settings: *plugin-sccache-read-only

  update_cache:
    image: quay.io/radicle_garden/plugin-sccache:latest
    when:
      evaluate: 'CI_PIPELINE_EVENT == "push" && CI_COMMIT_BRANCH == CI_REPO_DEFAULT_BRANCH && CI_COMMIT_MESSAGE startsWith "Release"'
    volumes:
      - sccache:/sccache_data
    settings:
      <<: *plugin-sccache-read-only
      save-if: true

  build-arch:
    image: docker.io/library/archlinux:base-devel
    when:
      - path: "arch/*/*"
      - event: manual
    commands:
      - pacman -Sy --noconfirm git
      - useradd -m builder
      - 'echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder'
      - chown -R builder:builder /home/builder
      - su builder
      - set -e
      - cd /home/builder
      - rm -rf radicle-bin && git clone https://aur.archlinux.org/radicle-bin.git --depth=1
      - makepkg --dir radicle-bin --install --syncdeps --noconfirm
      - cd $CI_WORKSPACE/arch/radicle-desktop
      # Ensure .SCRINFO is up-to-date
      - makepkg --printsrcinfo > .SRCINFO && git diff --exit-code .SRCINFO
      - |
          CI=true \
          BUILDDIR=/home/builder/build \
          PKGDEST=/home/builder/ \
          SRCDEST=/home/builder/ \
          makepkg --syncdeps --noconfirm --force
