when:
  - event: pull_request
  - event: push
    branch: main

variables:
  - &plugin-sccache-read-only
    s3-bucket: "build-caches"
    s3-endpoint: "https://minio-api.radworks.garden"
    s3-key-prefix: "radicle-desktop"
    save-if: "false"
    s3-access-key:
      from_secret: minio_access_key
    s3-secret-access-key:
      from_secret: minio_secret_key

# test

steps:
  read_cache:
    image: quay.io/radicle_garden/plugin-sccache:latest
    volumes:
      - sccache:/sccache_data
    settings: *plugin-sccache-read-only

  update_cache:
    image: quay.io/radicle_garden/plugin-sccache:latest
    when:
      evaluate: 'CI_PIPELINE_EVENT == "push" && CI_COMMIT_BRANCH == CI_REPO_DEFAULT_BRANCH && CI_COMMIT_MESSAGE startsWith "Release"'
    volumes:
      - sccache:/sccache_data
    settings:
      <<: *plugin-sccache-read-only
      save-if: true

  end-to-end:
    image: quay.io/radicle_garden/radicle-desktop-e2e:latest
    volumes:
      - sccache:/sccache_data
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        set -euo pipefail

        export PATH="/sccache_data:$PATH"
        source .sccache

        ./scripts/install-binaries;
        npm ci
        npm run build:http
        mkdir -p tests/artifacts;

        # Install and run playwright
        npm run test:e2e -- --project webkit

        sccache --show-stats
