when:
  - event: pull_request
  - event: push
    branch: main

steps:
  unit-tests:
    image: docker.io/library/node:22.11.0
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        npm ci
        npm run test:unit
