name: check-e2e
on: push

jobs:
  check-e2e:
    strategy:
      matrix:
        browser: [webkit]
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        run: npm ci

      - name: Build test-http-api
        run: npm run build:http

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-dep-cache
        with:
          path: ~/Library/Caches/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}

      - name: Install Playwright browsers
        if: steps.playwright-dep-cache.outputs.cache-hit != 'true'
        run: npx playwright install webkit

      - name: Install Radicle binaries
        run: |
          mkdir -p tests/artifacts;
          ./scripts/install-binaries;

      - name: Run Playwright tests
        run: npm run test:e2e -- --project ${{ matrix.browser }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-artifacts-${{ runner.os }}
          retention-days: 30
          if-no-files-found: "ignore"
          path: |
            tests/artifacts/**/*
