name: radicle-desktop
on: push

jobs:
  lint-ts:
    name: lint typescript
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run check-js
  lint-rust:
    name: lint rust
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crates/radicle-tauri
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgtk-3-dev libsoup-3.0-dev libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-dev
          version: 1.0
      - run: npm run check-rs
