on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: node:22.11.0

    steps:
      - uses: actions/checkout@v4

      - name: Cache node_modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - run: npm ci
        if: steps.cache-npm.outputs.cache-hit != 'true'

      - run: npm run test:unit
