// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CodeRange = {
  "type": "lines";
  range: { start: number; end: number };
} | { "type": "chars"; line: number; range: { start: number; end: number } };
