// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "../Author";
import type { Edit } from "../patch/Edit";
import type { Embed } from "./Embed";
import type { Never } from "../Never";
import type { Reaction } from "../Reaction";

export type Comment<T = Never> = {
  id: string;
  author: Author;
  edits: Array<Edit>;
  reactions: Array<Reaction>;
  replyTo: string | null;
  location: T | null;
  embeds?: Array<Embed>;
  resolved: boolean;
};
