// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Embed } from "./Embed";

export type NewIssueComment = {
  id: string;
  body: string;
  replyTo?: string;
  embeds?: Array<Embed>;
};
