// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comment } from "./Comment";
import type { Never } from "../Never";

export type Thread<T = Never> = {
  root: Comment<T>;
  replies: Array<Comment<T>>;
};
